"""add twitter linkedin youtube columns

Revision ID: 3d53ad26234f
Revises: fbcb45f983e8
Create Date: 2026-03-20 17:51:50.131200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d53ad26234f'
down_revision = 'fbcb45f983e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('youtube', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('youtube')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('twitter')

    # ### end Alembic commands ###
