"""add learn more fields

Revision ID: d290bb93eae2
Revises: d19e4ad25510
Create Date: 2026-03-17 11:39:28.119009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd290bb93eae2'
down_revision = 'd19e4ad25510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('languages', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('profession', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('passions', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('studies', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('alcohol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tobacco', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('food_preference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('children', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('children')
        batch_op.drop_column('allergies')
        batch_op.drop_column('food_preference')
        batch_op.drop_column('tobacco')
        batch_op.drop_column('alcohol')
        batch_op.drop_column('school')
        batch_op.drop_column('studies')
        batch_op.drop_column('passions')
        batch_op.drop_column('profession')
        batch_op.drop_column('languages')

    # ### end Alembic commands ###
