"""add evaluations table

Revision ID: fbcb45f983e8
Revises: d290bb93eae2
Create Date: 2026-03-20 09:28:43.436474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcb45f983e8'
down_revision = 'd290bb93eae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('evaluated_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('was_present', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['evaluated_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'evaluator_id', 'evaluated_id', name='uq_evaluation')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_evaluated_id'), ['evaluated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_evaluator_id'), ['evaluator_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_evaluator_id'))
        batch_op.drop_index(batch_op.f('ix_evaluations_evaluated_id'))
        batch_op.drop_index(batch_op.f('ix_evaluations_activity_id'))

    op.drop_table('evaluations')
    # ### end Alembic commands ###
